export default {
  SET_COUNT_ARTICLES: "SET_COUNT_ARTICLES",
  SET_ARTICLES: "SET_ARTICLES",
  SET_FOUND_ARTICLES: "SET_FOUND_ARTICLES",
  SET_FLAG: "SET_FLAG",
  SET_INDIVIDUALS: "SET_INDIVIDUALS",
  SET_PAGE: "SET_PAGE",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
  SET_INSTANCES: "SET_INSTANCES",
  SET_APPREF: "SET_APPREF"
}
